/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sat Dec 15 21:32:42 2018. */

#include "DataPacket.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DataPacket_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, DataPacket, packet_type, packet_type, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, DataPacket, identifier, packet_type, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, DataPacket, value, identifier, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
